# Generated by Django 4.2.4 on 2023-09-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_salesorder_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorder',
            name='description',
        ),
        migrations.AddField(
            model_name='salesorder',
            name='date_of_purchase',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
