# Generated by Django 4.2.4 on 2023-09-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(choices=[('th', 'technice'), ('bk', 'book'), ('ph', 'phone'), ('fd', 'food'), ('cl', 'cloth'), ('ot', 'other')], default='ot', max_length=2),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='other', max_length=225),
        ),
        migrations.AddField(
            model_name='product',
            name='product_photo',
            field=models.ImageField(default='-', upload_to='photos/%Y/%m/%d/'),
        ),
    ]
