# Generated by Django 4.2.4 on 2023-09-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_description_product_product_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_name',
        ),
        migrations.AddField(
            model_name='product',
            name='description_category',
            field=models.CharField(choices=[('th', 'technice'), ('bk', 'book'), ('ph', 'phone'), ('fd', 'food'), ('cl', 'cloth'), ('ot', 'other')], default='ot', max_length=2),
        ),
        migrations.AddField(
            model_name='product',
            name='receipt_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(default='None', max_length=500),
        ),
    ]
